const Strings = {
  userWelcome: 'We will keep you safe',
  placeholderSearch: 'Search Anythings...',
  emergency: 'Tab in case of Emergency',
  callpolice: 'Call Police',
  callFire: 'Call Fire',
  callambulance: 'Call Ambulance',
  callrakshak: 'Call Rakshak',
  emergencyContact: 'Emergency Contact',
  callNow: 'Call Now',
  calling: 'Calling ...',
  moreDetails: 'More Details',
  headerVideoTitle: 'Self Help Videos',
  searchVideo: 'Search Video',
  alert: 'youtube Alert',
  yoga: 'Yoga',
  tips: 'Tips',
  login: 'Login',
  loginAccess: 'Login to Access your travelwise account',
  placeholderEmail: 'john.doe@gmail.com',
  placeholderPassword: '...................',
  email: 'Email',
  password: 'Password',
  rememberMe: 'Remember Me',
};
export default Strings;
